### ISSUE TITLE
Secrets for pushing and pulling

### ISSUE THREAD

**Issue by theoriginalgri** [cloudflare/serverless-registry#38]
Great project you've done here!

Currently there's only the option to have a user/token that can pull and push images.

It would be great to have the ability to have a user/token that can only pull images so that it can be used in a safer way.

**Comment by ndejong** [comment]
+1 on this request, and +1 on the kudos.

The ability to maintain separation between tokens/identities that can push to repo -vs- those that can pull from repo is an important capability - currently it's not possible to use this project in the context of user-endpoints or build-pipelines because it implies you are giving the ability to modify your own trusted repo to those contexts.

Love where this project is going, happy days.

**Comment by gabivlj** [comment]
The JWT mechanism is designed around an external third party being able to generate a JWT for the registry and should be stable. I completely agree we should be providing easier ways to have read-only credentials!
